### ISSUE TITLE
What do we think of getting our own domain to run on instead of keeping everything on Bluemix?

### ISSUE THREAD

**Issue by ghost** [ybordag/CoderDojoLeaderboard#2]
I think it might be good if we start with a free domain [.tk & .ml come to mind] and set Bluemix up to run the website on the domain. That OR we can port the data over to the FTP protocol.

As for providers, 000webhost comes to mind as one that seems quite reliable and that we can get for free. I use 000webhost for my site and it appears to work completely fine. Thoughts?

**Comment by ashtov** [comment]
Why NOT Bluemix? If coderdojoleaderboard.mybluemix.net is too long to type
we can just create an is.gd or bit.ly url or something. I looked at those
.tk and .ml domains; they require your site to be up the ENTIRE TIME,
otherwise they suspend you for "domain squatting." That won't work for us
since we have to reboot the server whenever we change anything. In the
future we can look at getting a better domain, but for now, especially
since we need to get the tablet app out, it should be fine.

**Comment by arjavrawal** [comment]
Sounds good to me. I'll get a bit.ly set up right now. 

On Thu, 14 May 2015 11:29:26 -0700, MeFigaYoma  wrote: Why NOT Bluemix? If
coderdojoleaderboard.mybluemix.net is too long to type
 we can just create an is.gd or bit.ly url or something. I looked at those
 .tk and .ml domains; they require your site to be up the ENTIRE TIME,
 otherwise they suspend you for "domain squatting." That won't work for us
 since we have to reboot the server whenever we change anything. In the
 future we can look at getting a better domain, but for now, especially
 since we need to get the tablet app out, it should be fine.

 On Thursday, May 14, 2015, Arjav Rawal wrote:

 > I think it might be good if we start with a free domain [.tk & .ml come
to
 > mind] and set Bluemix up to run the website on the domain. That OR we
can
 > port the data over to the FTP protocol.
 >
 > As for providers, 000webhost comes to mind as one that seems quite
 > reliable and that we can get for free. I use 000webhost for
my site and
it
 > appears to work completely fine. Thoughts?
 >
 > --
 > Reply to this email directly or view it on GitHub
 > .
 >

--
Reply to this email directly or view it on GitHub [1].      
Warm regards,
Arjav Rawal
COO, Eternity Incurakai Studios
arjav@eternitech.tk
arjav@arjavrawal.tk
 

Links:
------
[1]
https://github.com/ybordag/CoderDojoLeaderboard/issues/2#issuecomment-102128244

**Comment by ghost** [comment]
Sounds good to me. I'll go ahead and set a bit.ly up right now.

**Comment by ashtov** [comment]
Didn't I just say we don't need it because we're working on the mobile app
first anyway?

On Thursday, May 14, 2015, Arjav Rawal notifications@github.com wrote:

> Sounds good to me. I'll get a bit.ly set up right now.
> 
> On Thu, 14 May 2015 11:29:26 -0700, MeFigaYoma wrote: Why NOT Bluemix? If
> coderdojoleaderboard.mybluemix.net is too long to type
> we can just create an is.gd or bit.ly url or something. I looked at those
> .tk and .ml domains; they require your site to be up the ENTIRE TIME,
> otherwise they suspend you for "domain squatting." That won't work for us
> since we have to reboot the server whenever we change anything. In the
> future we can look at getting a better domain, but for now, especially
> since we need to get the tablet app out, it should be fine.
> 
> On Thursday, May 14, 2015, Arjav Rawal wrote:
> 
> > I think it might be good if we start with a free domain [.tk & .ml come
> > to
> > mind] and set Bluemix up to run the website on the domain. That OR we
> > can
> > port the data over to the FTP protocol.
> > 
> > As for providers, 000webhost comes to mind as one that seems quite
> > reliable and that we can get for free. I use 000webhost for
> > my site and
> > it
> > appears to work completely fine. Thoughts?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> Warm regards,
> Arjav Rawal
> COO, Eternity Incurakai Studios
> arjav@eternitech.tk <javascript:_e(%7B%7D,'cvml','arjav@eternitech.tk');>
> arjav@arjavrawal.tk <javascript:_e(%7B%7D,'cvml','arjav@arjavrawal.tk');>
> 
> ## Links:
> 
> [1]
> 
> https://github.com/ybordag/CoderDojoLeaderboard/issues/2#issuecomment-102128244
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ybordag/CoderDojoLeaderboard/issues/2#issuecomment-102136508
> .

## 

MeFigaYoma

**Comment by ghost** [comment]
Whoops, wrong person, meant to send that to someone else :D sorry about
that.

Although, if you want a bit.ly link that won't work for you, go to http://bit.ly/komokphase3 :smile:
